### ISSUE TITLE
Weird Leave Lightning Bug

### ISSUE THREAD

**Issue by Zoyus** [TeamMidnightDust/BetterLeavesPack#13]
I am using:
Minecraft 1.16.5
Forge with Optifine
Ressourcepack: Better-Leaves-5.2
Shader: SEUS-Renewed-v1.0.1

Some lightsources cause this lighting bug:
![2021-06-15_13 16 52](https://user-images.githubusercontent.com/9790042/122043723-f660c100-cddb-11eb-8ae6-de934efc2f78.png)

**Comment by Motschen** [comment]
OptiFine has already caused a few issues with this pack and forge doesn't make it better.
I literally can't fix this in a resourcepack since that's weird vanilla behavior that is especially noticable with optifine. 
Even if I created a mod to change the relevant code it would not work with optifine, since OF replaces huge sections of vanilla code with it's own code that can't be accessed legally.
