### ISSUE TITLE
BetterEnd leaves not bushy anymore

### ISSUE THREAD

**Issue by lxly9** [TeamMidnightDust/BetterLeavesPack#28]
Yes, as the title says. 
It would be a pretty great addition if you could add to the models to render as normal blocks in the inventory, as the leaf block's bushes collide with other items in inventory mods such as EMI or REI. Furthermore after checking the files, it appears some leaf blocks don't even have models, yet they still display bushier leaves but are missing these in the inventory (Blighted Balsa from Biome Makeover DOES have models but no lbushes in the inventory, the other Biome Makeover leaves DO NOT have models yet they still possess bushes.)

Better End leaves DO NOT have bushier leaves even though they have models (not all of them do though, only 3). They also DO NOT render in the inventory.

![image](https://user-images.githubusercontent.com/102386118/197184184-e4b56191-e16d-4a89-9eb4-4cab25a9baae.png)
![2022-10-21_13 18 25](https://user-images.githubusercontent.com/102386118/197184202-d863f447-f5bd-441a-ad14-567071ad6fa5.png)

These inconsistencies really mess with parity in modpacks and especially in the one I'm currently deving.

**Comment by Motschen** [comment]
These inconsistencies happen when mods don't use Minecraft's "leaves.json" model as the parent model for their leaves.
Better Leaves includes a custom leaves.json model in order to support mods that don't have official support.
As a consequence, models that have it as the parent model will also be bushy in the inventory.
There's not much I can do about it, as this current solution allows for the widest compatibility.
As for the BetterEnd leaves, I added support for them, but maybe an update broke them, I'll look into that.

**Comment by lxly9** [comment]
Wouldn’t you in theory be able to make a leaf_block.json file which would be referenced as the blockitem model? Or is that not possible?

**Comment by Motschen** [comment]
That is possible, but would have to be done for every single leaf form every single mod.

**Comment by Motschen** [comment]
To correctly register BetterEnd bushy leaves, you have to restart the game.
